-- MySQL Script generated by MySQL Workbench
-- Fri Sep 22 19:16:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_id`)
);

-- -----------------------------------------------------
-- Table `mydb`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sucursales` (
  `sucursales_id` INT NOT NULL,
  `turno_id` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`sucursales_id`),
  CONSTRAINT `fk_turno_id` -- Nombre de la restricción de clave foránea
    FOREIGN KEY (`turno_id`) -- Columna que hace referencia a la clave foránea
    REFERENCES `mydb`.`Turnos` (`turnos_id`) -- Tabla y columna de referencia
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table `mydb`.`Turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turnos` (
  `turnos_id` INT NOT NULL,
  `esta_disponible` TINYINT NOT NULL DEFAULT 1,
  `dia` DATE NULL,
  `horario` VARCHAR(45) NULL,
  `tipo_servicio` VARCHAR(45) NULL,
  `sucursal_id` INT NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`turnos_id`),
  CONSTRAINT `fk_sucursal_id` -- Nombre de la restricción de clave foránea
    FOREIGN KEY (`sucursal_id`) -- Columna que hace referencia a la clave foránea
    REFERENCES `mydb`.`sucursales` (`sucursales_id`) -- Tabla y columna de referencia
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_id` -- Nombre de la restricción de clave foránea
    FOREIGN KEY (`usuario_id`) -- Columna que hace referencia a la clave foránea
    REFERENCES `mydb`.`Usuario` (`usuario_id`) -- Tabla y columna de referencia
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table `mydb`.`trabajadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trabajadores` (
  `trabajadores_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `esta_disponible` TINYINT NULL,
  `turno_id` INT NULL,
  `sucursal_id` INT NULL,
  PRIMARY KEY (`trabajadores_id`),
  CONSTRAINT `fk_sucursal_id_trabajadores` -- Nombre de la restricción de clave foránea
    FOREIGN KEY (`sucursal_id`) -- Columna que hace referencia a la clave foránea
    REFERENCES `mydb`.`sucursales` (`sucursales_id`) -- Tabla y columna de referencia
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turno_id_trabajadores` -- Nombre de la restricción de clave foránea
    FOREIGN KEY (`turno_id`) -- Columna que hace referencia a la clave foránea
    REFERENCES `mydb`.`Turnos` (`turnos_id`) -- Tabla y columna de referencia
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
